[package]
name = "chimitheque_back"
version = "0.1.0"
edition = "2024"
authors = ["Thomas Bellembois <thomas.bellembois@proton.me>"]
description = "Backend for Chimithèque"
license = "GPL-3.0"
repository = "https://github.com/tbellembois/chimitheque_back"
homepage = "https://github.com/tbellembois/chimitheque_back"
readme = "README.md"
categories = ["database", "science"]
keywords = ["chemistry", "biology", "database", "management"]
rust-version = "1.94.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8.8", features = ["macros"]}
axum-extra = { version = "0.12.3", features = ["query"] }
casbin = { git = "https://github.com/casbin/casbin-rs.git", branch = "copilot/fix-db-connection-in-operator-function", default-features = false, features = ["runtime-async-std", "logging", "incremental"] }
dashmap = { version = "6.1.0", default-features = false }
dotenvy = { version = "0.15", default-features = false }
erased-serde = { version = "0.3.31", default-features = false }
governor = { version = "0.10.4", default-features = false, features = ["quanta"] }
http = { version = "1.4.0", default-features = false }
jsonwebtoken = { version = "10.2.0", default-features = false, features = ["rust_crypto"]}
once_cell = { version = "1.21.3", default-features = false }
opentelemetry = { version = "0.22", default-features = false, features = ["trace"] }
opentelemetry-otlp = { version = "0.15", default-features = false, features = ["grpc-tonic", "http-proto"] }
opentelemetry_sdk = { version = "0.22", default-features = false, features = ["rt-tokio"] }
r2d2 = { version = "0.8.10", default-features = false }
r2d2_sqlite = { version = "0.32.0", default-features = false }
regex = { version = "1.12.2", default-features = false }
rusqlite = { version = "0.38.0", default-features = false, features = ["load_extension", "bundled"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.149", default-features = false }
thiserror = { version = "2.0.17", default-features = false }
tokio = { version = "1.10.0", default-features = false, features = ["fs", "io-util", "rt-multi-thread"] }
tower-http = { version = "0.6", default-features = false, features = ["cors","trace"] }
tower-sessions = { version = "0.14", default-features = false, features = ["memory-store"] }
tracing = { version = "0.1.44", default-features = false }
tracing-opentelemetry = { version = "0.23", default-features = false }
tracing-subscriber = { version = "0.3.22", default-features = false, features=["env-filter", "json", "fmt", "ansi"] }
ureq = { version = "3", default-features = false, features = ["json"] }
url = { version = "2.5.7", default-features = false }
uuid = { version = "1.19.0", default-features = false }

chimitheque_types = { git = "https://github.com/tbellembois/chimitheque_types.git", branch = "main" }
chimitheque_traits = { git = "https://github.com/tbellembois/chimitheque_traits.git", branch = "main" }
chimitheque_utils = { git = "https://github.com/tbellembois/chimitheque_utils.git", branch = "main" }
chimitheque_db = { git = "https://github.com/tbellembois/chimitheque_db.git", branch = "main" }
chimitheque_pubchem = { git = "https://github.com/tbellembois/chimitheque_pubchem.git", branch = "main" }

[patch."https://github.com/tbellembois/chimitheque_types.git"]
chimitheque_types = { path = "../chimitheque_types" }

[patch."https://github.com/tbellembois/chimitheque_traits.git"]
chimitheque_traits = { path = "../chimitheque_traits" }

[patch."https://github.com/tbellembois/chimitheque_utils.git"]
chimitheque_utils = { path = "../chimitheque_utils" }

[patch."https://github.com/tbellembois/chimitheque_db.git"]
chimitheque_db = { path = "../chimitheque_db" }

[patch."https://github.com/tbellembois/chimitheque_pubchem.git"]
chimitheque_pubchem = { path = "../chimitheque_pubchem" }
